# Generated by Django 5.2.2 on 2025-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_album_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
