# Generated by Django 5.2.2 on 2025-06-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_song_title_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
