# Generated by Django 5.2.2 on 2025-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_album_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('songs', models.ManyToManyField(related_name='playlists', to='base.song')),
            ],
        ),
    ]
