# Generated by Django 5.2.2 on 2025-11-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_playlist_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('feed_url', models.TextField()),
                ('podcast_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='play_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('episode_image', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField()),
                ('downloaded_url', models.TextField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='base.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_links', to='base.album')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='base.storageservice')),
            ],
        ),
    ]
