# Generated by Django 5.2.2 on 2025-11-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_podcast_storageservice_song_play_url_podcastepisode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('book_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioBookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('file_url', models.TextField()),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='base.audiobook')),
            ],
        ),
        migrations.CreateModel(
            name='AudioBookStorageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_links', to='base.audiobook')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_links', to='base.storageservice')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastStorageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_links', to='base.podcast')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_links', to='base.storageservice')),
            ],
        ),
    ]
