# Generated by Django 5.2.2 on 2025-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_audiobook_audiobookchapter_audiobookstoragelink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiobookchapter",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="podcaststoragelink",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="storagelink",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
