# Generated by Django 5.2.2 on 2025-11-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_audiobookchapter_note_podcaststoragelink_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageservice",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
